databases:
    mediawiki:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: enwiki # just a default, queries already specify it

defaults:
    db: mediawiki

reports:
    uploads:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    image-uploads:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    audio-uploads:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    video-uploads:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    deletions:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    uploaders:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    new-uploaders:
        granularity: months
        starts: 2004-01-01
        by_wiki: true
    upload-wizard-uploads:
        granularity: months
        starts: 2010-01-01
        by_wiki: true
    cross-wiki-uploads:
        granularity: months
        starts: 2015-09-01
        explode_by:
            wiki_db: commonswiki
