databases:
    mediawiki:
        host: "analytics-store.eqiad.wmnet"
        port: 3306
        creds_file: /a/.my.cnf.research
        db: enwiki # just a default, queries already specify it

defaults:
    db: mediawiki

reports:
    uploads:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    image-uploads:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    audio-uploads:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    video-uploads:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    deletions:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    uploaders:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    new-uploaders:
        granularity: months
        starts: 2004-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    upload-wizard-uploads:
        granularity: months
        starts: 2010-01-01
        explode_by:
            wiki_db: wiki_dbs.txt
    cross-wiki-uploads:
        granularity: months
        starts: 2015-09-01
        explode_by:
            wiki_db: commonswiki
    upload-wizard-uploads:
        granularity: days
        starts: 2017-01-01
        funnel: true
    upload-wizard-errors:
        granularity: days
        starts: 2017-01-01
        funnel: true
    upload-wizard-api-errors:
        granularity: days
        starts: 2017-01-01
        funnel: true
